### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by GeoffreyPlitt** [optroot/watch-later#2]
In the last few days, the plugin seems to have stopped working; I can right-click and choose the "add to watch later" entry, but then when I go check my YouTube watch-later, the video isn't there.

Maybe there's an API-call error that is being hidden?

**Comment by optroot** [comment]
Hmm, I didn't change anything so I'll take a look at the API, and hopefully have this fixed soon.

**Comment by optroot** [comment]
The links from before still work for me, can you confirm? Can you supply some examples of links not working?

https://www.youtube.com/attribution_link?a=Hq24fjMoa-I&u=/watch%3Fv%3D0LbKgi9_Gyg%26feature%3Dem-uploademail

https://www.youtube.com/attribution_link?a=3vl00gWknyc&u=/watch%3Fv%3DxfP6IkpfgqQ%26feature%3Dem-uploademail

If you go to Setting > Extensions and open up the 'background page', it should give you a more verbose description of what is going on.

Error code 409 is for duplicate videos, 404 if the video doesn't exist, and 400 if there is missing or invalid information.

**Comment by GeoffreyPlitt** [comment]
All working now, sorry, may have been an intermittent error! From now on I'll know how to look deeper for those error codes. Thanks again.
